sudo: false

language: node_js

node_js:
  - 9
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn all:test

cache:
  yarn: true
  directories:
    - $HOME/.cache
    - node_modules
